sudo: false
language: node_js
node_js:
- node
install: npm install
script:
- npm test
- gulp
addons:
  ssh_known_hosts: 138.68.27.217
branches:
  only:
  - master
  - develop
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_490c55ea7bee_key -iv $encrypted_490c55ea7bee_iv
  -in travis_rsa.enc -out travis_rsa -d
deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
  on:
    all_branches: true
